version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - '3001:3000'
    volumes:
      - './src:/var/www'
      - './php/local.ini:/usr/local/etc/php/conf.d/local.ini'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
  webserver:
    image: 'nginx:alpine'
    restart: unless-stopped
    tty: true
    depends_on:
      - mysql
      - app
    ports:
      - '83:80'
      - '446:443'
    volumes:
      - './src:/var/www'
      - './nginx/conf.d/:/etc/nginx/conf.d/'
    networks:
      - app-network
  mysql:
    image: 'mysql:8'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    tty: true
    ports:
      - '3309:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - 'dbdata:/var/lib/mysql/'
      - './mysql/my.cnf:/etc/my.cnf'
    networks:
      - app-network
  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
    - '6380:6379'
    networks:
      - app-network
    volumes:
    - 'db_redis:/data'
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
  db_redis:
    driver: local
